### ISSUE TITLE
Suggestion: Throw error when em-dash detected in input

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2cli#107]
New linux users periodically end up with the em-dash in their commands, which breaks the script in a opaque way.

Would it be possible to throw an explicit and constructive error or warning any time an em-dash is detected in the input?

(Thank you to @ebolyen for the feedback!)

**Comment by ebolyen** [comment]
:tada:

**Comment by colinbrislawn** [comment]
Wow, @jairideout's cool clean code would have saved [this qiime1 user](https://groups.google.com/forum/#!topic/qiime-forum/omwXKPVG0nY). 

Well done.

**Comment by jairideout** [comment]
Thanks @colinbrislawn, but that was @jakereps' 1337 code :P  I'm glad this fix is in for qiime2, and thanks again for reporting it!

**Comment by colinbrislawn** [comment]
Finally some user feedback! Looks like our fix didn't help this specific user. https://forum.qiime2.org/t/plugin-error-feature-classifier-extract-reads/2493 

Let's wait and see... It may be worth reopening this issue and improve the listed error.

**Comment by jairideout** [comment]
Thanks @colinbrislawn! Do you have suggestions for how to improve the error message? If you have availability/interest in submitting a Pull Request with a clearer error message, we'd really appreciate it!

**Comment by colinbrislawn** [comment]
Here's a [user story](https://forum.qiime2.org/t/error-with-my-filtering-feature-table-command/5133/) that illustrates the ongoing issue with MS Word auto insert of 'smart quotes' and em-dashes.

Matt resolves this by calling out the specific symbols, and directly comparing them to the normal, linux-friendly ones. 

> Do you have suggestions for how to improve the error message?

I think the real solution is not to write an error message at all, but to do what Matt did here. 1) show the user that there is are small differences between symbols `“ ” vs " "` 2) show the user what symbols they are using, 3) suggest a fix.

I think a positive outcome is to have the user post on the forums where we can give them the long explanation. In both these examples, the users had more questions once we resolved the characters, and they had already started the conversation.
