### ISSUE TITLE
tab-completion breaks on multi-line commands

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2cli#116]
e.g. commands in the QIIME 2 docs. Not sure if this is fixable or something we have to live with in `bash`.

**Comment by ebolyen** [comment]
This is not possible to fix in bash as it's readline interface [specifically branches on empty lines](https://github.com/bminor/bash/blob/64447609994bfddeef1061948022c074093e9a9f/lib/readline/examples/fileman.c#L261-L281)

This works fine in ZSH though as discovered by @thermokarst
