### ISSUE TITLE
BUG: `qiime tools view` checks for $DISPLAY which isn't set on OS X

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2cli#121]
We should check if `uname` is `Darwin` and if so, assume we have a windowed environment.

**Comment by jakereps** [comment]
Oh interesting, looks like XQuartz (which my $DISPLAY shows) was installed with either my GIMP or R installation, as looking online both require it. I can snag this one since my environment gave a false positive on the initial "fix" for this.
