### ISSUE TITLE
show importable type choices for `qiime tools import`

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2cli#124]
The `--type` option in `qiime tools import` is free text and requires the user to know the relevant importable type expression ahead of time. It would be useful to display a list of types that are valid inputs to `--type` (i.e. concrete semantic types that are associated with a directory format).

The set of importable type expressions will be available from the framework via `qiime2.sdk.PluginManager.importable_types` once https://github.com/qiime2/qiime2/pull/216 is merged.

There are a few routes I can think of to accomplish this:

- Make `--type` a `click.Choice` option instead of free text (see [here](http://click.pocoo.org/5/options/#choice-options) for an example). This renders pretty terribly, especially with `|` being overloaded:

  <img width="1420" alt="screen shot 2017-02-13 at 3 24 04 pm" src="https://cloud.githubusercontent.com/assets/1847232/22906324/37370826-f201-11e6-945f-7bd2009b0f61.png">

- Keep `--type` as free text and display choices in help text:

  <img width="584" alt="screen shot 2017-02-13 at 3 22 48 pm" src="https://cloud.githubusercontent.com/assets/1847232/22906368/6e47d0c0-f201-11e6-97f3-9560fee0e5a7.png">

- Have an [eager option](http://click.pocoo.org/5/options/#callbacks-and-eager-options) (e.g. similar to `--help` and `--version`) that shows the choices and exits. Something like a `--show-importable-types` option.

- Have a separate command to display importable types.

@gregcaporaso, @ebolyen, @thermokarst, @jakereps: what do you guys think? Any preferences, or maybe a better way to solve this?

**Comment by gregcaporaso** [comment]
I like the eager option here, since there is potentially so much information.

**Comment by thermokarst** [comment]
👍 for eager option

**Comment by jairideout** [comment]
👍 I'm down with that too. I remember discussion about QIIME 1's eager flags (e.g. `beta_diversity.py --show_metrics`) being frowned on but I can't remember who didn't like them, or why. Maybe the source of frustration was how they had to be implemented with `qcli` and not the user-facing side? At least Click has first-class support for eager options.
