### ISSUE TITLE
Support for --silent

### ISSUE THREAD

**Issue by wasade** [qiime2/q2cli#125]
In general, the output information about what artifacts are created is very useful (and I really like clean use of colors). However, there are times when it would be nice to not have this output (e.g., scripting). This could be exposed, similar to the `--verbose` flag as a `--silent` flag, in which output normally directed to stdout is not shown.

**Comment by jairideout** [comment]
👍, maybe `-q`/`--quiet` to match pip and conda?

**Comment by wasade** [comment]
I like that too. Both seem common, perhaps --quiet more so.

It would be great if this trapped output from contained system calls as
well (when possible)

**Comment by jairideout** [comment]
Subprocess calls have their output silenced by default. `--verbose` sends the output to stdout/stderr. I may be misunderstanding what you mean by "contained system calls" though.

**Comment by wasade** [comment]
I'm getting messages like the following:

```bash
Running external command line application. This may print messages to stdout and/or stderr.
The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.

Command: mafft --preservecase /var/folders/bm/2__q0f_s3p19hvlsd_p_2tn80000gn/T/q2-DNAFASTAFormat-mm2bj_ph
```

...although, based on our slack conversation, this may be due to using the method directly (e.g., `q2_alignment.mafft` instead of `from qiime2.plugins import alignment; alignment.methods.mafft`

**Comment by wasade** [comment]
If I make the method calls via the API, I also get output. This is separate from q2cli I believe though

```python
> from qiime2 import Artifact
> ar = Artifact.load('foo.qza')
> deblur.methods.denoise_16S(ar, 100)
Results (name = value)
---------------------------------------------------------------------------------------------------------
table                    = <artifact: FeatureTable[Frequency] uuid: 61140f35-273d-463f-92b3-dca572b63416>
representative_sequences = <artifact: FeatureData[Sequence] uuid: d6e208b7-08bf-4fb7-af20-074992b7b2d5>
```

**Comment by jairideout** [comment]
Yeah that's intended behavior for the Python API (the "Artifact API"). The CLI traps that output by default unless `--verbose` is set.
