### ISSUE TITLE
Support for variadic arguments

### ISSUE THREAD

**Issue by wasade** [qiime2/q2cli#152]
As referenced in the click [documentation](http://click.pocoo.org/5/arguments/#variadic-arguments). The specific use case motivating this issue is to expose [`biom.Table.concat`](http://biom-format.org/documentation/generated/biom.table.Table.concat.html#biom.table.Table.concat) which is about 100x faster than `biom.Table.merge` in general, and additionally, supports an arbitrary number of `Table` instances. From the user perspective, this results in a substantial performance boost and a more succinct interface. In other words, the current form of:

```bash
$ qiime feature-table merge \
  --i-table1 table-1.qza \
  --i-table2 table-2.qza \
  --o-merged-table merged-table.qza
$ qiime feature-table merge \
  --i-table1 merged-table.qza \
  --i-table2 table-3.qza \
  --o-merged-table merged-table.qza
$ qiime feature-table merge \
  --i-table1 merged-table.qza \
  --i-table2 table-4.qza \
  --o-merged-table merged-table.qza
```

Could be expressed as:

```bash
$ qiime feature-table merge \
  --i-table table-1.qza \
  --i-table table-2.qza \
  --i-table table-3.qza \
  --i-table table-4.qza \
  --o-merged-table merged-table.qza
```

**Comment by jairideout** [comment]
We'll need to support variadic arguments in the framework first before interfaces can use these types of function signatures. There's also an issue on `q2-feature-table` to support merging arbitrary numbers of tables, so I'll close this issue in favor of:

https://github.com/qiime2/qiime2/issues/234
https://github.com/qiime2/q2-feature-table/issues/103

**Comment by jairideout** [comment]
Note: qiime2 `Metadata` merging is supported in q2cli using click's multi-options, see [this section of the metadata tutorial](https://docs.qiime2.org/2017.7/tutorials/metadata/#combining-metadata).
