### ISSUE TITLE
Passing in a visualization gives cryptic error

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2cli#165]
This [came up on the forum](https://forum.qiime2.org/t/getting-error-when-performing-diversity-core-metrics-phylogenetic/1446). It looks like we're getting an error because [this line](https://github.com/qiime2/q2cli/blob/2273ccce1a8934cb41b1269d855207e6b1948721/q2cli/handlers.py#L302) errors without knowing the context. So a user who passes in a `qzv` will see something about using `Visualization.load` instead.

**Comment by gregcaporaso** [comment]
I got this today as well.

**Comment by jairideout** [comment]
came up again on the forum: [x-ref](https://forum.qiime2.org/t/error-message-of-qiime-diversity-core-metrics-phylogenetic-step/2589?u=jairideout)
