### ISSUE TITLE
explore options for caching command parameters

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#2]
@wasade points out that with a lot of plugins/workflows, building the commands is going to become a bottleneck.

**Comment by wasade** [comment]
We probably should profile with mock plugins to see where the bottlenecks to test, but it would be awesome to have the response time of a call to `qiime` down to sub 100ms

**Comment by jairideout** [comment]
Click recommends [multi commands](http://click.pocoo.org/5/commands/#custom-multi-commands) for lazily loading commands from plugins. Not sure about caching but this might help with the performance issues.

**Comment by wasade** [comment]
Oh, good find
