### ISSUE TITLE
BUG: Range not displayed by Click

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2cli#210]
**Bug Description**
Ranges specified during plugin registration (e.g. [in vsearch cluster-features-de-novo](https://github.com/qiime2/q2-vsearch/blob/0fcd6fffd6c82c98ebbf5482dc9bc28669f34254/q2_vsearch/plugin_setup.py#L52)) are not expressed by Click in user docs (e.g. [here](https://docs.qiime2.org/2018.11/plugins/available/vsearch/cluster-features-de-novo/)) or in CLI help . 

Related to q2-vsearch issue [1](https://github.com/qiime2/q2-vsearch/issues/1). 
[Forum xref](https://forum.qiime2.org/t/error-float-object-has-no-attribute-type-in-otu-clustering/8087) showing incorrect user inputs related to this.

**Steps to reproduce the behavior**
See [```--p-perc-identity FLOAT``` parameter](https://docs.qiime2.org/2018.11/plugins/available/vsearch/cluster-features-de-novo/), OR run ```qiime vsearch cluster-features-de-novo --help```

**Expected behavior**
Docs should display parameter ranges. Ideally, this would be handled programatically rather than on a parameter-by-parameter basis. 

**Computation Environment**
- LinuxMint 18
- QIIME 2 2018.11

**Comment by ebolyen** [comment]
fixed in #212
