### ISSUE TITLE
No space on device error masked as not-an-artifact error

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2cli#213]
**Bug Description**
When $TMPDIR has insufficient space, q2cli will report that an artifact is not an artifact, while the actual problem is that `Artifact.load` failed with an out of space error (likely OSError 28, but I haven't confirmed that). The problematic branch [is here](https://github.com/qiime2/q2cli/blob/3d14e0db66f3f070d91904c9ce73b1fee34aa659/q2cli/click/type.py#L100-L104).

**Steps to reproduce the behavior**
1.  Create a $TMPDIR such that it has very little space (e.g. 2G).
2.  Run something that involves a classifier which is large (or perhaps upstream sequence data)

Example:
```
§ qiime feature-classifier classify-sklearn --i-classifier ~/tst/silva-132-99-515-806-nb-classifier.qza --i-reads ~/tst/rep-seqs.qza --o-classification taxonomy.qza
```
Produces:
```
                  There were some problems with the command:                  
 (1/2) Invalid value for "--i-classifier":
  '/home/evan/tst/silva-132-99-515-806-nb-classifier.qza' is not a QIIME 2
  Artifact (.qza)
 (2/2) Invalid value for "--i-reads": '/home/evan/tst/rep-seqs.qza' is not a
  QIIME 2 Artifact (.qza)
```

**Expected behavior**
We should see the underlying problem reported in user-friendly language.

```
There was not enough space left on <directory> to extract the artifact <path>.   (Try setting $TMPDIR to a directory with more space, or increase the size of <directory>.)
```

Language obviously subject to change/improvement.

**Computation Environment**
- `$TMPDIR` with insufficient space

**Questions**
1. The specific error returned by this situation should be verified.

**Comments**
1. I edited `/etc/fstab` and rebooted a few times to reproduce. This was the easiest for me, but other options include creating new mount points and setting quotas on those partitions.
1. An API in the framework which can say whether a file is a QIIME 2 artifact with the answers of "yes", "no", and "probably, but corrupted beyond repair" would be helpful here.
1. Tests may not be possible to write without something like a FUSE test fixture, which is probably overkill at this time.

**References**
1. https://forum.qiime2.org/t/error-in-using-pre-trained-silva-classifier/9798/5
2. https://github.com/qiime2/q2cli/blob/3d14e0db66f3f070d91904c9ce73b1fee34aa659/q2cli/click/type.py#L100-L104

**Comment by ebolyen** [comment]
fixed in #214

**Comment by ecologysarah** [comment]
@ebolyen FYI, this bug is still occurring in version 2021.8

**Comment by s-andrews** [comment]
I've also seen this but I think with a different cause.  I believe in my case that it was an out of memory error as it was running on a cluster node with a low memory assignment.  The exact same command later ran with no problems after giving more resources to the job.

```
$ qiime feature-classifier classify-sklearn --i-classifier 515f-806r-animal-distal-gut-classifier.qza --i-reads rep-seqs_240.qza --o-classification taxonomy_240.qza
Usage: qiime feature-classifier classify-sklearn [OPTIONS]
[Removed standard help page stuff here]

                  There were some problems with the command:
 (1/2) Invalid value for '--i-classifier': '515f-806r-animal-distal-gut-
  classifier.qza' is not a QIIME 2 Artifact (.qza)
 (2/2) Invalid value for '--i-reads': 'rep-seqs_240.qza' is not a QIIME 2
  Artifact (.qza)

```

This is on;

```$ qiime --version
q2cli version 2022.8.0```
