### ISSUE TITLE
BUG: `qiime extract` suggested by `qiime tools view --help` is not a command

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2cli#215]
**Bug Description**
The `qiime tools view` helptext suggests the command `qiime extract`, which is not a command. 

**Steps to reproduce the behavior**
1. In a working QIIME 2 environment, enter the command `qiime tools view --help'.
2. Enter the suggested command, `qiime extract`, and note the error message. 

**Expected behavior**
Helptext should suggest `qiime tools extract`.

**Screenshots**
![qiime_tools_extract](https://user-images.githubusercontent.com/39198770/58899989-14ef3600-86b3-11e9-9f02-a46eba928001.png)
![no-extract](https://user-images.githubusercontent.com/39198770/58899999-191b5380-86b3-11e9-9a13-bc8a929c9ae5.png)

**Computation Environment**
- OS: linuxmint 18.11
- QIIME 2 2019.4

**Comment by thermokarst** [comment]
LOC to be changed: https://github.com/qiime2/q2cli/blob/master/q2cli/builtin/tools.py#L277
