### ISSUE TITLE
Input checking should happen before the classifier runs

### ISSUE THREAD

**Issue by JCSzamosi** [qiime2/q2cli#231]
**Bug Description**
If you give `--o-classifier` a path to a file in a non-existent directory, it waits until after the classifier has run (sometimes several hours) before raising a FileNotFoundError.

**Steps to reproduce the behavior**
Run `qiime feature-classifier fit-classifier-naive-bayes --o-classifier output/directory/file.qza` where `output/directory/` does not exist. 

**Expected behavior**
It should either raise a FileNotFoundError within seconds or create the directory with a warning.

**Computation Environment**
- Linux of some kind (It's a Compute Canada cluster)

**Comment by ebolyen** [comment]
Oh no! I really though I had solved this one in the last refactor. Thanks for reporting!
