### ISSUE TITLE
ZSH 5.8 Tab Completion Error When Activating QIIME2 Environment

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2cli#255]
**Bug Description**
Error when activating qiime2 conda environment.

**Steps to reproduce the behavior**

Command Line:
conda activate qiime2-2021.2

Resultant error:
complete:13: command not found: compdef

**Computation Environment**
- OS: macOS Big Sur
- ZSH: 5.8
- BASH: -
- miniconda: conda 4.9.2
- QIIME 2 Release: 2021.2

**References**
1. Same error message, different OS:
https://forum.qiime2.org/t/qiime2-not-working-on-macos-catalina/18858

**Comment by lizgehret** [comment]
This command resolved the issue locally: 
`autoload compinit && compinit && autoload bashcompinit && bashcompinit && source tab-qiime`

**Comment by andrewsanchez** [comment]
In addition to the bit of code `conda init` adds to .zshrc, I also have `autoload -U compinit && compinit` in [my .zshrc](https://github.com/andrewsanchez/dotfiles-plus/blob/30830b41548be95caece291fe3eeb580886593ce/.zshrc#L53-L68)

**Comment by lizgehret** [comment]
`autoload -Uz compinit && compinit && autoload bashcompinit && bashcompinit && source tab-qiime
`
