### ISSUE TITLE
BUG: q2cli usage handing bad type expressions to framework when TypeMap

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2cli#264]
**Bug Description**
q2cli sends invalid type expressions to the framework for parsing, when generating usage examples for TypeMaps

**Steps to reproduce the behavior**
1. Activate a QIIME 2 env newer than 2021.2
2. run `qiime feature-table merge --examples`
3. Observe error (abbreviated below):

```
(q2-dev) chris@tumbleBox:~/src/qiime2/q2cli (master)> qiime feature-table merge --examples
# ### example: basic ###
Traceback (most recent call last):
  File "/home/chris/miniconda/envs/q2-dev/lib/python3.8/site-packages/qiime2/core/type/parse.py", line 16, in string_to_ast
    parsed = ast.parse(type_expr)
  File "/home/chris/miniconda/envs/q2-dev/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    FeatureTable[Frequency]¹ | FeatureTable[RelativeFrequency]²
                           ^
SyntaxError: invalid character in identifier

...
```
**Computation Environment**
- OS: linux, probably irrelevant here
- QIIME 2 Release 2019.4. Bug found and confirmed in 2021.2, .4, .8. (feature-table merge got TypeMapped in 2021.2)

**Questions**
1. `_template_metadata` also hands type expressions to util.parse_type(). Are Metadata/MetadataCategory type expressions also annotated with superscript numerals?
2. Where does the addition of superscript numbers actually happen?

**Details**
Since [2019.4](url), q2cli has added superscript numbers to types when working with TypeMaps.

> TypeMaps are indicated with a superscript number which will match between inputs and outputs. (In the future, a table may be a better way to represent this).

When `usage.py` [sends these type expressions out to the framework](https://github.com/qiime2/q2cli/blob/037a6accde6838fe1d4e28ef2763f2c2446259f6/q2cli/core/usage.py#L205) for parsing, the framework hands them off to the standard library's `ast.parse(type_expr)`, which chokes on the superscript characters. *

The usage examples for q2_feature_table's `merge` were created before `merge` was TypeMapped, so the issue didn't pop up until 2021.2. There are no tests in place for TypeMapped Actions.

**References**
- [where q2cli ships out the bad type expressions](https://github.com/qiime2/q2cli/blob/037a6accde6838fe1d4e28ef2763f2c2446259f6/q2cli/core/usage.py#L205)
- [the proximal/apparent breaking change](https://github.com/qiime2/q2-feature-table/blob/221cdd3368c0c6da494f4d1d50ac7365fb592e38/q2_feature_table/plugin_setup.py#L177)

**Comment by thermokarst** [comment]
Fixed in #267
