### ISSUE TITLE
add option that will allow the cli to not block

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#3]

**Comment by jairideout** [comment]
It looks like Python will always block and wait for its futures at system exit time (see [here](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown)). We'll have to revisit non-blocking execution, not sure offhand how best to fix this.

**Comment by wasade** [comment]
Makes sense as the subprocess is a child, so at exit (process termination) the children will be killed as well. For this to work, it likely needs to be that the processes are daemonized, at which point, I don't know how we could appropriately capture stdout/stderr

**Comment by jairideout** [comment]
This issue is no longer relevant. The "Artifact API" supports synchronous and asynchronous execution and the CLI is correctly using sync execution. If we support a non-blocking CLI in the future it'll likely be an entirely different CLI project/package (q2cli is designed to be QIIME 1-like).
