### ISSUE TITLE
q2cli should hide actions with names that start with `_`

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#301]
- `_` shouldn't be replaced with `-`
- actions starting with underscores should be hidden by default, with a flag to include them in the list when called as `qiime plugin-name`

**Comment by Oddant1** [comment]
@gregcaporaso when you say `_` shouldn't be replaced with `-`, I interpreted that as only the leading `_` shouldn't be replaced. Is that how you intended it?

e.g. `_underscore_method` should show up in the list as `_underscore-method`

**Comment by gregcaporaso** [comment]
Yes, that's correct @Oddant1.
