### ISSUE TITLE
enable direct-to-cache imports

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#317]
To speed up import of very large data sets, we should be able to directly import data (e.g., a collection of `fastq.gz` files) to an artifact cache, without going through an Archive (`.qza`). This would avoid the zipping of the large dataset.

**Comment by Oddant1** [comment]
I moved this to the cli because this is actually totally possible in the Python API by doing the following:

```
cache = Cache(path)

art = Artifact.import_data(type, view)
cache.save(art)
```

**Comment by ebolyen** [comment]
@Oddant1, I created another issue for a slightly different problem: https://github.com/qiime2/qiime2/issues/730
