### ISSUE TITLE
`--citations` should report plugin citations when called on an action

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#336]
[Forum x-ref](https://forum.qiime2.org/t/default-citations-for-a-plugin-action-function-transformer-etc/29562/6)

Current behavior:

```shell
$ qiime hello-metagenome --citations
% use `qiime tools citations` on a QIIME 2 result for complete list

@misc{key0,
 author = {Caporaso, J Gregory and Bolyen, Evan},
 howpublished = {https://develop.qiime2.org},
 title = {Developing with QIIME 2},
 year = {2024}
}

$ qiime hello-metagenome duplicate-table --citations
No citations found.
```

Desired behavior:
The action-level `--citations` report should include all of the citations from the plugin-level `--citations` report.

**Comment by Oddant1** [comment]
@gregcaporaso I opened a PR that should close this and requested your review on it to make sure it's doing what you wanted.
