### ISSUE TITLE
plugin citation and user support text should be accessible

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2cli#40]
We should try to fit this in with the project URLs here:

![screenshot 2016-08-04 15 42 03](https://cloud.githubusercontent.com/assets/192372/17420958/f45de828-5a5a-11e6-90e9-4cc5e8447a1f.png)

Also, a statement after the one at the very bottom saying something like: "Also, please remember to cite plugins..."

This is really important for motivating developers to write plugins, and we'll want something like this in all of our interfaces.

**Comment by jairideout** [comment]
Fixed in #43.
