### ISSUE TITLE
Should `qiime tools citations` be `qiime info citations`?

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2cli#47]
It seems like it is more of an info command as it only side-effects stdout.

**Comment by jairideout** [comment]
Discussed this with @ebolyen. Moving `tools citations` command to `info --citations` flag, which is off by default. This is similar to `info`'s `--py-packages` flag. `info` doesn't take any arguments and purely provides info about the current QIIME deployment, so the current citations support makes sense as part of that command. When there is more advanced support for citations, a `tools citations` command makes sense, to generate citations from an artifact/visualization (in possibly more than one output format).
