### ISSUE TITLE
add `qiime tools provenance` command

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2cli#70]
**Comments**
It'd be best to wait for the new provenance support @ebolyen is working on before adding this command.

**Comment by ElDeveloper** [comment]
Would this issue address being able to print the commands that were used to create each artifact?

**Comment by jairideout** [comment]
It could! This issue is waiting on some sort of framework API for parsing/querying/manipulating provenance. We never really discussed exactly what `qiime tools provenance` would do, besides displaying some graphical representation of provenance (e.g. similar to view.qiime2.org). Having some way to recover the q2cli commands that were run would be really really cool!

We could definitely use some help on the framework to support interacting with provenance -- that would let interfaces, such as q2cli, become provenance-aware.

**Comment by ElDeveloper** [comment]
This sounds like fun!

**Comment by Oddant1** [comment]
@colinvwood I''m thinking we can close this now with prov replay being merged
